-- Q Replication Health Check
SELECT 
  SUBSTR(SOURCE_NAME,1,20) AS SOURCE,
  SUBSTR(TARGET_NAME,1,20) AS TARGET,
  STATUS,
  LAST_SENT_TIMESTAMP,
  LAST_RECEIVED_TIMESTAMP
FROM ASN.IBMQREP_APPLYPARMS;
